### ISSUE TITLE
Checklist for Publishing the GeoPose 1.0 Draft Standard

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/GeoPose#53]
Now that the document is in metanorma-asciidoc, we will go through the following steps to release:

**Standards Document**

- [ ] Review the Standards Document - Check typos
- [ ] Review the Standards Document - Check Requirements Classes
- [ ] Review the Standards Document - Check Requirements
- [ ] Review the Standards Document - Check Conformance Classes
- [ ] Review the Standards Document - Check Conformance Tests
- [ ] Review the Standards Document - Check references to schemas.opengis.net
- [ ] Review the Standards Document - Check references to Figures
- [ ] Review the Standards Document - Check references to Tables
- [ ] Review the Standards Document - Check "Unresolved directive" errors (i.e. dangling includes)
- [ ] Review the Standards Document - Check for broken links
- [ ] Notify OGC Infrastructure Office that the document is ready for publishing
- [ ] Check that the document has been published

**schemas.opengis.net**

- [ ] Create ticket for publishing the schema files at schemas.opengis.net
- [ ] Check that the schema files have been published at schemas.opengis.net

**Comment by ghobona** [comment]
Related issue affecting Requirements Class tables https://github.com/metanorma/metanorma-ogc/issues/434
